version: '3.8'

services:
  # api:
  #   build:
  #     context: ../
  #     dockerfile: docker/Dockerstaging
  #   container_name: korrectsports_api_staging
  #   env_file:
  #     - ../.env
  #   volumes:
  #     - ../:/app
  #   ports:
  #     - "80:8000"
  #   depends_on:
  #     - db
  #   networks:
  #     - korrectsports_staging

  api:
    image: benidevo/korrectsports-api:staging
    container_name: korrectsports_api_staging
    env_file:
      - ../.env
    ports:
      - "80:8000"
    depends_on:
      - db
      - adminer
    networks:
      - korrectsports_staging

  db:
    image: mysql:8.0
    container_name: korrectsports_db_staging
    restart: always
    env_file:
      - ../.env
    volumes:
      - db_data_staging:/var/lib/mysql
    networks:
      - korrectsports_staging

  adminer:
    image: adminer:4.8.1
    container_name: korrectsports_adminer_staging
    restart: always
    ports:
      - 8080:8080
    networks:
      - korrectsports_staging

volumes:
  db_data_staging:

networks:
  korrectsports_staging:
    driver: bridge
